### ISSUE TITLE
[BUG] CSV Export fails if component inside DataGrid has input masks

### ISSUE THREAD

**Issue by phucduong86** [formio/formio#1106] opened 2020-10-07 18:32 UTC
## Environment
Please provide as many details as you can:

- Hosting type
  - [ ] Form.io
  - [x] Local deployment
    - Version: Application: 7.100.0, Renderer: 4.12.0
- Formio.js version: not relevant
- Frontend framework: not relevant
- Browser: any
- Browser version: not relevant

## Steps to Reproduce
1. Create a new form
2. Add a Data Grid component (disable Table View)
3. Drop a Text Field Component inside the Data Grid component (Enable Table view for this component)
4. Create an input mask for the Text Field Component (eg: 999-999-9999)
5. Publish the form and create a submission
6. Go to form's Data tab
7. Click Export CSV

## Expected behavior
The CSV should be exported with the submitted data.

## Observed behavior
It takes a long time for the download prompt to come up (30-60 seconds), the CSV come out empty

8. Remove input mask from the Text Field component and publish the form
9. Return to the form's Data tab
10. Click Export CSV

## Observed behavior:
The download prompt comes up instantly, and the data is displayed properly in the exported file.

**Comment by wag110894** [comment] 2020-10-07 21:32
Hello @phucduong86, 

The Application: 7.100.0 build is for a customer and should not have been latest. The latest should be changed. Can you try and see if the issue is resolved with updating to the new latest?

**Comment by phucduong86** [comment] 2020-10-07 23:53
Hi Will,

The latest is working fine. Thank you for your response.
Do you usually have a tagged version that is the same as latest? It would make it easier for us to manage the application (so we don't have to retag "latest")

Thank you

**Comment by wag110894** [comment] 2020-10-08 13:53
You can check and see the latest version of formio.js here: https://github.com/formio/formio.js/blob/master/Changelog.md.

**Comment by phucduong86** [comment] 2020-10-08 14:05
@wag110894 
I am actually looking for the formio-enterprise (portal) container tagged version that match the **formio-enterprise:latest**
Would it be documented somewhere?

Thank you

**Comment by wag110894** [comment] 2020-10-08 14:12
Thanks for the clarity. The formio enterprise is actually our server that has the portal inside. You can see the server versions (and the version of the portal that it is in the server version) here: https://github.com/formio/formio-server/blob/master/Changelog.md

I hope that this helps.

**Comment by phucduong86** [comment] 2020-10-08 15:59
Hi Will,

I am referring to specific tags on this page https://hub.docker.com/r/formio/formio-enterprise/tags
We manage our server deployment by pulling specific tagged docker image whichever matches the signature of the latest tag.

Unfortunately the release note above does not tell us which docker image tag it corresponds to.

This is not a major issue but does add a step to our process (retag "latest" to a unique tag for tracking purpose).

**Comment by lane-formio** [comment] 2024-01-31 14:30
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.

**Closed by lane-formio** 2024-01-31 14:30 UTC
Labels: bug
