### ISSUE TITLE
authentication not working with select component

### ISSUE THREAD

**Issue by gismomtl** [formio/formio#667] opened 2018-10-12 19:37 UTC
the x-jwt-token is not transmitted even if "Formio authenticate" is checked in a select component.
when using select component, with URL as source type, even if "Formio authenticate" is checked, no x-jwt-token is transmitted.
Because of that, "read all" access to the ressource need to be set to Anonymous if we want to be able to use the form.
To verify, if we add manually in the request header the "x-jwt-token" with a valid temp token, connection is working to a Authenticated "read all" ressource. 
we cannot use the Ressource as source type for different reason. We are using formio itself as URL source type.
we have an Angular app in front of formio.

formio version: 1.33.5

**Comment by wag110894** [comment] 2018-10-15 19:04
Hello,
 
Thanks for reaching out! 
 
We are unable to replicate this issue on our end as the x-jwt-token is included in our header. 
The issue may be that you are not logged into your application to include the JWT token.
 
Please let me know if you have any further questions or concerns.
 
Thanks, 
William Gay 
Form.io Developer Support

**Comment by gismomtl** [comment] 2018-11-02 17:00
the way I was able to solve it is via:
add in the Request Header:
   Key "x-jwt-token"
   Value "{{ Formio.token }}"

I'm using formio 1.35.2 and angular-formio 1.18.0

**Comment by ZenMasterJacob20011** [comment] 2024-02-07 14:27
Closing this thread as it is outdated and the issue is not reproducible. Please re-open if it is still relevant. Thank you for your contribution!

**Closed by ZenMasterJacob20011** 2024-02-07 14:27 UTC
