### ISSUE TITLE
[BUG] Number and currency component issue. Doesn't  get cleared.

### ISSUE THREAD

**Issue by mukeshrk** [formio/formio#823] opened 2019-08-08 17:49 UTC
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version:
- Frontend framework:
- Browser:
- Browser version:

## Steps to Reproduce
1. Add Number / Currency component in form builder
2.  Go to renderer and enter number
3. Click backspacke slowly to remove the number.

## Expected behavior
It should clear the number.
## Observed behavior
It doesn't clear the last number
![Number](https://user-images.githubusercontent.com/29056610/62725477-d3706380-ba32-11e9-8289-3a361928dc31.gif)

## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

For code or form JSON, please enclose in a code block:

```js
// your code here
```

**Comment by travist** [comment] 2019-08-08 20:40
This definitely looks like a bug. We will take a look.

**Comment by gshivam44** [comment] 2019-08-09 07:41
I am also facing this issue.
Not only backspace, the issue can also be observed if we select all and delete/backspace or select all and cut.

**Comment by jhen1422** [comment] 2019-08-09 15:18
@mukeshrk 
Thank you for the report.
We have added this item to our backlog and will discuss this in our weekly planning meeting next week. If you would like to expedite this issue, please email support@form.io for cost information.

Thank you!

**Comment by mukeshrk** [comment] 2019-08-14 05:47
@jhen1422 
Nah, i can wait until the bug is fixed. But it will be more helpful if you can fix ASAP.
:)

Thank you very much for adding in your backlog.

**Comment by anonymousonline** [comment] 2019-08-17 13:41
I can confirm that I am also facing this issue. For me i discovered it when i noticed my fields were also not updating when clearing number components.

**Comment by jhen1422** [comment] 2019-09-10 19:58
@mukeshrk @anonymousonline 
This has been resolved in the latest version of our 4x renderer

**Closed by jhen1422** 2019-09-10 19:58 UTC
Labels: bug
