### ISSUE TITLE
Error: Could not locate the bindings file

### ISSUE THREAD

**Issue by Arifi** [formio/formio#218] opened 2016-12-06 21:47 UTC
Hi
Im trying to run formio but i got this error

`Error: Could not locate the bindings file. Tried:
 → C:\Users\Mourad\formio\node_modules\bcrypt\build\bcrypt_lib.node
 → C:\Users\Mourad\formio\node_modules\bcrypt\build\Debug\bcrypt_lib.node
 → C:\Users\Mourad\formio\node_modules\bcrypt\build\Release\bcrypt_lib.node
 → C:\Users\Mourad\formio\node_modules\bcrypt\out\Debug\bcrypt_lib.node
 → C:\Users\Mourad\formio\node_modules\bcrypt\Debug\bcrypt_lib.node
 → C:\Users\Mourad\formio\node_modules\bcrypt\out\Release\bcrypt_lib.node
 → C:\Users\Mourad\formio\node_modules\bcrypt\Release\bcrypt_lib.node
 → C:\Users\Mourad\formio\node_modules\bcrypt\build\default\bcrypt_lib.node
 → C:\Users\Mourad\formio\node_modules\bcrypt\compiled\4.2.6\win32\x64\bcrypt_lib.node
    at bindings (C:\Users\Mourad\formio\node_modules\bcrypt\node_modules\bindings\bindings.js:88:9)
    at Object.<anonymous> (C:\Users\Mourad\formio\node_modules\bcrypt\bcrypt.js:3:35)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\Mourad\formio\src\util\encrypt.js:3:14)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Function.router.init (C:\Users\Mourad\formio\index.js:55:29)`

Any idea ?

Thank you

**Comment by zackurben** [comment] 2016-12-12 21:05
Duplicate of https://github.com/formio/formio/issues/143

@Arifi sorry for the delay, I'll try to look into this asap

**Comment by Arifi** [comment] 2016-12-12 21:47
@zackurben thank you
It will be good if we can try formio, we are exploring such tools :)

**Comment by zackurben** [comment] 2016-12-12 21:59
@Arifi if you have a second, do you mind pulling in a custom branch and trying to install it?

in the formio directory:

```
git pull origin bugfix/fix-win-install
npm i
```

let me know if that fixes the issue.

**Comment by Arifi** [comment] 2016-12-13 12:59
sure, on it :)

**Comment by Arifi** [comment] 2016-12-13 13:22
Hi @zackurben 

I got this 

`C:\Users\Mourad\Documents\formio>npm i
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade

> bcrypt@1.0.1 install C:\Users\Mourad\Documents\formio\node_modules\bcrypt
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download: https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.1/bcrypt_lib-v1.0.1-node-v46-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for bcrypt@1.0.1 and node@4.2.6 (node-v46 ABI) (falling back to source compile with node-gyp)
/
C:\Users\Mourad\Documents\formio\node_modules\bcrypt>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" clean )  else (node  clean )
\
C:\Users\Mourad\Documents\formio\node_modules\bcrypt>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure --fallback-to-build --module=C:\Users\Mourad\Documents\formio\node_modules\bcrypt\lib\binding\bcrypt_lib.node --module_name=bcrypt_lib --module_path=C:\Users\Mourad\Documents\formio\node_modules\bcrypt\lib\binding --python=C:\Users\Mourad\.windows-build-tools\python27\python.exe --msvs_version=2015 )  else (node  configure --fallback-to-build --module=C:\Users\Mourad\Documents\formio\node_modules\bcrypt\lib\binding\bcrypt_lib.node --module_name=bcrypt_lib --module_path=C:\Users\Mourad\Documents\formio\node_modules\bcrypt\lib\binding --python=C:\Users\Mourad\.windows-build-tools\python27\python.exe --msvs_version=2015 )`

**Comment by Arifi** [comment] 2016-12-13 13:26
So i tryed this link [(https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.1/bcrypt_lib-v1.0.1-node-v46-win32-x64.tar.gz)]

and got a 404

**Comment by Arifi** [comment] 2016-12-13 16:24
hi @zackurben 

I deleted the folder node_modules and i tryed again, this time it finished but i got lot of errors

```
C:\Users\Mourad\Documents\formio>npm install
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN optional dep failed, continuing fsevents@1.0.15
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

> bcrypt@1.0.1 install C:\Users\Mourad\Documents\formio\node_modules\bcrypt
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download: https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.1/bcrypt_lib-v1.0.1-node-v46-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for bcrypt@1.0.1 and node@4.2.6 (node-v46 ABI) (falling back to source compile with node-gyp)
-
C:\Users\Mourad\Documents\formio\node_modules\bcrypt>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" clean )  else (node  clean )
-
C:\Users\Mourad\Documents\formio\node_modules\bcrypt>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure --fallback-to-build --module=C:\Users\Mourad\Documents\formio\node_modules\bcrypt\lib\binding\bcrypt_lib.node --module_name=bcrypt_lib --module_path=C:\Users\Mourad\Documents\formio\node_modules\bcrypt\lib\binding --python=C:\Users\Mourad\.windows-build-tools\python27\python.exe --msvs_version=2015 )  else (node  configure --fallback-to-build --module=C:\Users\Mourad\Documents\formio\node_modules\bcrypt\lib\binding\bcrypt_lib.node --module_name=bcrypt_lib --module_path=C:\Users\Mourad\Documents\formio\node_modules\bcrypt\lib\binding --python=C:\Users\Mourad\.windows-build-tools\python27\python.exe --msvs_version=2015 )
/
C:\Users\Mourad\Documents\formio\node_modules\bcrypt>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" build --fallback-to-build --module=C:\Users\Mourad\Documents\formio\node_modules\bcrypt\lib\binding\bcrypt_lib.node --module_name=bcrypt_lib --module_path=C:\Users\Mourad\Documents\formio\node_modules\bcrypt\lib\binding )  else (node  build --fallback-to-build --module=C:\Users\Mourad\Documents\formio\node_modules\bcrypt\lib\binding\bcrypt_lib.node --module_name=bcrypt_lib --module_path=C:\Users\Mourad\Documents\formio\node_modules\bcrypt\lib\binding )
Génération des projets individuellement dans cette solution. Pour activer la génération en parallèle, ajoutez le commutateur "/m".
  blowfish.cc
  bcrypt.cc
  bcrypt_node.cc
..\src\bcrypt.cc(232): warning C4267: '=': conversion from 'size_t' to 'unsigne
d char', possible loss of data [C:\Users\Mourad\Documents\formio\node_modules\b
crypt\build\bcrypt_lib.vcxproj]
..\src\bcrypt_node.cc(76): warning C4244: 'argument': conversion from 'ssize_t'
 to 'unsigned char', possible loss of data [C:\Users\Mourad\Documents\formio\no
de_modules\bcrypt\build\bcrypt_lib.vcxproj]
..\src\bcrypt_node.cc(229): warning C4267: 'initializing': conversion from 'siz
e_t' to 'int', possible loss of data [C:\Users\Mourad\Documents\formio\node_mod
ules\bcrypt\build\bcrypt_lib.vcxproj]
..\src\bcrypt_node.cc(230): warning C4267: 'initializing': conversion from 'siz
e_t' to 'int', possible loss of data [C:\Users\Mourad\Documents\formio\node_mod
ules\bcrypt\build\bcrypt_lib.vcxproj]
  win_delay_load_hook.c
C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\src\win_delay_lo
ad_hook.c(31): error C2373: '__pfnDliNotifyHook2': redefinition; different type
 modifiers [C:\Users\Mourad\Documents\formio\node_modules\bcrypt\build\bcrypt_l
ib.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\delayimp.h(134
  ): note: see declaration of '__pfnDliNotifyHook2'
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\Users\\Mourad\\Documents\\formio\\node_modules\\bcrypt\\lib\\binding\\bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=C:\\Users\\Mourad\\Documents\\formio\\node_modules\\bcrypt\\lib\\binding"
gyp ERR! cwd C:\Users\Mourad\Documents\formio\node_modules\bcrypt
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd build --fallback-to-build --module=C:\Users\Mourad\Documents\formio\node_modules\bcrypt\lib\binding\bcrypt_lib.node --module_name=bcrypt_lib --module_path=C:\Users\Mourad\Documents\formio\node_modules\bcrypt\lib\binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\Mourad\Documents\formio\node_modules\bcrypt\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:821:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Windows_NT 10.0.14393
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Mourad\\Documents\\formio\\node_modules\\bcrypt\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\Mourad\Documents\formio\node_modules\bcrypt
node-pre-gyp ERR! node -v v4.2.6
node-pre-gyp ERR! node-pre-gyp -v v0.6.30
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd build --fallback-to-build --module=C:\Users\Mourad\Documents\formio\node_modules\bcrypt\lib\binding\bcrypt_lib.node --module_name=bcrypt_lib --module_path=C:\Users\Mourad\Documents\formio\node_modules\bcrypt\lib\binding' (1)
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.2.6
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE

npm ERR! bcrypt@1.0.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@1.0.1 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Mourad\Documents\formio\npm-debug.log

C:\Users\Mourad\Documents\formio>
```

**Comment by Arifi** [comment] 2016-12-13 16:25
and when i run, i got this

```
C:\Users\Mourad\Documents\formio>node main

module.js:328
    throw err;
    ^

Error: Cannot find module 'bcrypt'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\Mourad\Documents\formio\src\util\encrypt.js:3:14)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Function.router.init (C:\Users\Mourad\Documents\formio\index.js:55:29)
    at module.exports (C:\Users\Mourad\Documents\formio\server.js:59:10)
    at Object.<anonymous> (C:\Users\Mourad\Documents\formio\main.js:5:20)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

C:\Users\Mourad\Documents\formio>
```

**Comment by zackurben** [comment] 2016-12-13 17:34
Hey @Arifi, thanks for working with me on this. It seems like I need to get my hands on a windows machine to fix any issues, or make some documentation for getting started with windows. I'll be following this when I do, if you too want to try it: http://stackoverflow.com/a/29438823

The issue is with bcrypt being dependent on some crypto libraries which come standard in *nix, but not in windows (yet). It looks like you can easily get them with the free download of MS Visual Studios, but I havent tried it yet.

**Comment by Arifi** [comment] 2016-12-13 18:04
@zackurben  Ah i see..

Sorry im not too familiar on node and i already loved it, otherwise i'll give more help
I'll fellow your link and see how i can help :)

Thx

**Comment by Arifi** [comment] 2016-12-13 18:19
@zackurben 

I tryed `npm install bcrypt` in empty folder, i got same error

[npm-debug.log.txt](https://github.com/formio/formio/files/649477/npm-debug.log.txt)

I'll report to bcrypt

**Comment by Arifi** [comment] 2016-12-13 18:20
@zackurben i fellowed the link instructions but didnt worked for me :/

**Comment by zackurben** [comment] 2017-01-23 17:24
This should be fixed now, see my final reply here: https://github.com/formio/formio/issues/143

**Closed by zackurben** 2017-01-23 17:24 UTC
Labels: duplicate, Windows

**Comment by Arifi** [comment] 2017-01-23 17:38
@zackurben thank you

Sorry i was not active, my PC got crashed :/
I'll check this ASAP
