### ISSUE TITLE
Will not run (fresh install) Windows 10 pro - node v - 6.0.0 npm -v 3.8.6

### ISSUE THREAD

**Issue by nigel-dewar** [formio/formio#546] opened 2018-02-21 22:53 UTC
Hi There,

I've tried running this project using node v8+ and then dropped down the node -v 6.0.0 to try and see if I could get it to work. I did this because it looked like the project was failing due to node version. But this makes no difference

npm ERR! Failed at the formio@1.25.8 version script 'check-node-version --node '>=6.0.0''.

I have mongo running fine. 

Here is the error I am getting

```
C:\Users\nigel\formio>npm start

> formio@1.25.8 start C:\Users\nigel\formio
> npm run version && node main.js


> formio@1.25.8 version C:\Users\nigel\formio
> check-node-version --node '>=6.0.0'

C:\Users\nigel\formio\node_modules\semver\semver.js:690
    throw new TypeError('Invalid comparator: ' + comp);
    ^

TypeError: Invalid comparator: '
    at Comparator.parse (C:\Users\nigel\formio\node_modules\semver\semver.js:690:11)
    at new Comparator (C:\Users\nigel\formio\node_modules\semver\semver.js:674:8)
    at C:\Users\nigel\formio\node_modules\semver\semver.js:840:12
    at Array.map (native)
    at Range.parseRange (C:\Users\nigel\formio\node_modules\semver\semver.js:839:13)
    at Range.<anonymous> (C:\Users\nigel\formio\node_modules\semver\semver.js:781:17)
    at Array.map (native)
    at new Range (C:\Users\nigel\formio\node_modules\semver\semver.js:780:40)
    at C:\Users\nigel\formio\node_modules\check-node-version\index.js:119:32
    at module.exports (C:\Users\nigel\formio\node_modules\map-values\index.js:9:18)

npm ERR! Windows_NT 10.0.16299
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "version"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! formio@1.25.8 version: `check-node-version --node '>=6.0.0'`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the formio@1.25.8 version script 'check-node-version --node '>=6.0.0''.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the formio package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     check-node-version --node '>=6.0.0'
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs formio
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls formio
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\nigel\formio\npm-debug.log

npm ERR! Windows_NT 10.0.16299
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! formio@1.25.8 start: `npm run version && node main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the formio@1.25.8 start script 'npm run version && node main.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the formio package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run version && node main.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs formio
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls formio
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\nigel\formio\npm-debug.log
```

I found however that doing a 'node main' command works and performs the install successfully.

So there is something wrong with the node version checker at least

Any ideas would be be very appreciated. Kind regards

Nige

**Comment by nigel-dewar** [comment] 2018-02-22 20:13
did a fresh install in another location and getting this error.

```
C:\test\formio>npm run start

> formio@1.25.8 start C:\test\formio
> node main.js


module.js:568
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module version mismatch. Expected 48, got 57.
    at Error (native)
    at Object.Module._extensions..node (module.js:568:18)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\test\formio\node_modules\bcrypt\bcrypt.js:6:16)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\test\formio\src\util\encrypt.js:3:16)

npm ERR! Windows_NT 10.0.16299
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! formio@1.25.8 start: `node main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the formio@1.25.8 start script 'node main.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the formio package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node main.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs formio
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls formio
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\test\formio\npm-debug.log
```

**Comment by nigel-dewar** [comment] 2018-02-22 20:30
So then I tried this, but now get a mongo_client.js error. I have confirmed mongo is up and running on the default port!

```
C:\test\formio>npm run start

> formio@1.25.8 start C:\test\formio
> node main.js


  __  __                          _       __
 / / / _| ___  _ __ _ __ ___     (_) ___  \ \
/ / | |_ / _ \| '__| '_ ` _ \    | |/ _ \  \ \
\ \ |  _| (_) | |  | | | | | | _ | | (_) | / /
 \_\|_|  \___/|_|  |_| |_| |_|(_)|_|\___/ /_/

Welcome to the Form.io application server!

  - Help: https://help.form.io
  - Code: https://github.com/formio
  - Love: https://form.io


C:\test\formio\node_modules\mongodb\lib\mongo_client.js:433
          throw err
          ^
MongoError: database name must be a string
    at Function.MongoError.create (C:\test\formio\node_modules\mongodb-core\lib\error.js:31:11)
    at validateDatabaseName (C:\test\formio\node_modules\mongodb\lib\db.js:1680:57)
    at new Db (C:\test\formio\node_modules\mongodb\lib\db.js:156:3)
    at Db.db (C:\test\formio\node_modules\mongodb\lib\db.js:1208:12)
    at C:\test\formio\src\db\index.js:126:19
    at connectCallback (C:\test\formio\node_modules\mongodb\lib\mongo_client.js:527:5)
    at C:\test\formio\node_modules\mongodb\lib\mongo_client.js:430:11
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! formio@1.25.8 start: `node main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the formio@1.25.8 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\nigel\AppData\Roaming\npm-cache\_logs\2018-02-22T20_28_15_564Z-debug.log

C:\test\formio>
```

**Comment by SergeyMNet** [comment] 2018-05-23 08:54
I already spent two days with try launch on win10 and nothing.

**Comment by A-Pradeep** [comment] 2018-05-30 17:56
The problem seems to be with the single quote in the package.json.

Replace
"check-node-version --node '>=6.0.0'"
with
"check-node-version --node \">=6.0.0\""

check once and it should be running fine , since im using in win10

**Comment by Ju2c0c0** [comment] 2018-06-17 23:15
Nice, it works! Just, do not forget to escape the double quotes or it will be invalid JSON:
```
"check-node-version --node \">=6.0.0\"" 
```

**Comment by Sidiro23** [comment] 2024-01-31 14:26
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.

**Closed by Sidiro23** 2024-01-31 14:26 UTC
