### ISSUE TITLE
Recaptcha component dont appear in form builder on form.io

### ISSUE THREAD

**Issue by gp1234** [formio/formio#955] opened 2020-03-29 18:17 UTC
The settings configuration let you add recaptcha's keys but the component dont appear. Any help with this?

**Comment by Alena-Levina** [comment] 2020-03-30 15:46
Hi @gp1234,

Form.io reCAPTCHA component implements [reCAPTCHA v3.](https://developers.google.com/recaptcha/docs/v3) which is not supposed to be visible ( except for the small badge in the bottom right corner of the webpage [like this](https://monosnap.com/file/xeDw5hY4ItStKRzCFzERKbBV6RFPLC) )

You can take a look at our [help docs](https://help.form.io/userguide/form-components/#recaptcha) regarding how to correctly configure reCAPTCHA component and make sure you didn't miss anything.

You could also take a look at our reCAPTCHA component usage example here for an additional insight: https://formio.github.io/formio.js/app/examples/recaptcha.html

If above doesn't explain the issue you're seeing, could you please describe the steps you take to reproduce the issue and attach a recording / screenshot of issue reproducing? Form JSON might also be helpful.

Regards,
Alena

**Comment by gp1234** [comment] 2020-03-30 16:35
Hello @Alena-Levina thank you very much for answering me, I found the recaptcha component using the new portal from form.io (https://next.form.io/) I follow the instructions in the provided help docs, the first screenshot dont appear as in the component in the page ( [screenshot from component](https://monosnap.com/file/0HxVtLS6rP1UBhnBm7Myoj5adiBCBM ) ) and when I save it this is what appears in my embedded form [link](https://monosnap.com/file/r1SCVt5bZQUtD3BVtZe1bAcazuX0dj?idx=0&total=1), not the badge. Thanks again,
Giovanni

**Comment by gp1234** [comment] 2020-03-30 21:22
Hello @Alena-Levina the issue occurs when I embed my form as an iframe, I try to use it with the links and google captcha do works, sadly I need to use the iframe option on my server. Do you know any workarounds?

**Comment by Alena-Levina** [comment] 2020-03-31 08:43
Hi @gp1234 ,

The screenshot you've provided looks like you're using version of renderer which doesn't know about reCAPTCHA component. What renderer (formio.js / angular-formio / ngFormio / react-formio) and what version of it do you use for rendering your form with reCAPTCHA component?

Also, could you please provide JSFiddle / Plunker / etc. of how you render your form?

Regards,
Alena

**Comment by daneformio** [comment] 2024-01-31 14:18
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!

**Closed by daneformio** 2024-01-31 14:18 UTC
Labels: bug
