### ISSUE TITLE
URL source items not populating Select Field

### ISSUE THREAD

**Issue by robgunston** [formio/formio#691] opened 2018-11-22 23:10 UTC
We are trying to use a select field populating from an external JSON API source (Order Desk), but no data is flowing through.

We have set entered the URL and Keys into form.io as per the 3rd party documentation, and believe we are referencing the correct JSON elements as follows - any ideas why this is not working?

URL: https://app.orderdesk.me/api/v2/inventory-items
Keys: ID and content type keys as required by Order Desk API

Data Path: **inventory_items**
Value Property: **id**
Item Template: **<span>{{ item.code }}</span>**

This is the JSON schema...

{
  "status": "success",
  "execution_time": "0.6651 seconds",
  "records_returned": 5,
  "total_records": "5",
  "inventory_items": [
    {
      "id": 2510,
      "name": "Three Wolf T-Shirt, X-Large / Black",
      "code": "3wolf-11",
      "price": 10,
      "cost": 8,
      "weight": 0.8,
      "stock": 48,
      "update_source": "Shopify",
      "location": "",
      "date_added": "2014-08-09 09:06:53",
      "date_updated": "2014-08-09 09:06:53"
    }
    {
      "id": 2515,
      "name": "White iPhone, White iPhone",
      "code": "whiteiphone",
      "price": 10,
      "cost": 8,
      "weight": 0.8,
      "stock": 108,
      "update_source": "Shopify",
      "location": "",
      "date_added": "2014-08-09 09:06:53",
      "date_updated": "2014-08-09 09:06:53"
    }
  ]
}

**Comment by randallknutson** [comment] 2018-11-26 15:35
Is your browser throwing an errors when you try to use the form? Typically with external APIs the issue is that the server is not responding properly to OPTIONS requests for CORS. If that happens the browser will block access to the API for security reasons. If that is the case you will need to have your api respond properly to the OPTIONS request.

**Comment by jeriah-formio** [comment] 2024-01-31 14:26
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!

**Closed by jeriah-formio** 2024-01-31 14:26 UTC
