### ISSUE TITLE
Please help: Postinstallation problems

### ISSUE THREAD

**Issue by michlm** [formio/formio#305] opened 2017-03-22 19:13 UTC
I installed Form.io on my linux deb. The installation suceeded, but when i try to sign in on the API-Platform i get the error: "TypeError: Could not connect to API server (Failed to fetch)"

**Comment by zackurben** [comment] 2017-03-23 21:46
Are you getting any errors starting the server?

**Comment by scotthellings** [comment] 2017-05-15 15:33
I too am having this problem with ubuntu server 16.04 any fix for this issue. I get no errors when starting the server.

I have tested using ubuntu desktop and everything works fine

**Comment by Roudaille77** [comment] 2017-07-10 16:01
I had the same problem. Resolved by installing Yarn

**Comment by mrksdiehl** [comment] 2017-08-06 09:16
I solved this by going into client/dist/config.js and edited APP_URL and API_URL to match my actual url

**Comment by A-Pradeep** [comment] 2018-08-17 07:49
@mrksdiehl  Hi can you tell what changes you did , even mine running in localhost itself even though i've changed it to like  www.example.com . but still when i hit `npm start` it end up in the `localhost:3001`

**Comment by robbieforder** [comment] 2018-08-21 20:58
There are a couple of variables in `formio/client/dist/config.js` which seem to be hardwired to localhost, just change these to your server name. Note this is not the file in the config directory which also references localhost, I changed that as well.

**Comment by A-Pradeep** [comment] 2018-08-22 05:03
hi, could you please elaborate the changes you made , so that i can find out the problem in my environment.

**Comment by bobslee** [comment] 2018-09-13 21:20
I changed "localhost" to the right host/URL in the 2 following files:
`app/dist/config.js` and `client/dist/config.js`

Both "Form.io management application" and the forms are now accessible.

**Comment by alanm101** [comment] 2019-07-29 05:17
@bobslee Thanks mate. This had me scratching my head.

**Comment by lalitver10** [comment] 2020-11-08 12:13
@bobslee Hii I did not able to  find any app/dist/config.js or client/dist/config.js directory. can you please help me where are these both directory
![directory](https://user-images.githubusercontent.com/58241512/98464574-d6d03d00-21e9-11eb-8b32-ca245c408c00.PNG)

**Comment by bobslee** [comment] 2020-11-08 14:13
@lalitver10 Unfortunately I can't help you. I don't use/experiment with the Formio platform stack anymore.

**Comment by multinerd** [comment] 2021-05-28 21:16
> 
> 
> @bobslee Hii I did not able to find any app/dist/config.js or client/dist/config.js directory. can you please help me where are these both directory

I was able to get it working using this env variable. No need to modify the json files.

```
NODE_CONFIG: '{"mongo": "mongodb://mongo:27017/formio", "domain": "https://example.com"}'
```

**Comment by PatrikTrefil** [comment] 2023-02-21 11:12
I believe the problem is that a prebuilt version of the client is downloaded, which was built to run on `localhost:3001`. There are three possible solutions to this problem. Either build the client during installation and allow passing arguments to this build, or make the client load its configuration from enviroment variables, which would be set in the docker-compose configuration file or just don't setup the client at all and let this be a responsibility of the user.

**Comment by PatrikTrefil** [comment] 2023-04-18 08:11
I finally figured out how to configure the app url and api url used by the client. When you open the client in the browser, you can pass `appUrl` and `apiUrl` in the query string. So, if you are hosting your client at `http://localhost:8080/formio/`, then you should access the client via `http://localhost:8080/formio/?appUrl=http%253A%252F%252Flocalhost%253A8080%252Fformio%252F&apiUrl=http%253A%252F%252Flocalhost%253A8080%252Fformio%252F` (the values of the `appUrl` and `apiUrl` params are URL encoded).

You obviously don't want to write this url every time, so you can reconfigure your reverse proxy to add it for you. Here is the if statement for the `^/formio/$` location:

```
if ($args !~ ^(?=.*\bappUrl=)(?=.*\bapiUrl=).*$) {
    return 301 /formio/?appUrl=http%3A%2F%2Flocalhost%3A8080%2Fformio%2F&apiUrl=http%3A%2F%2Flocalhost%3A8080%2Fformio%2F;
}
```

**Closed** 2024-01-24 14:44 UTC
Labels: help wanted
