### ISSUE TITLE
[BUG] when select component saves numeric data, then query result always returns empty

### ISSUE THREAD

**Issue by tmy2017** [formio/formio#982] opened 2020-04-27 06:27 UTC
Hi community! 

Already tried to look thorough the previous issues here on GitHub, and tried to look into the source code, but I figure still need some help here.

I am trying to query data from a select component which saves **numeric data**. But no matter how I try (used __regex, __eq, __lt, __gt), seems like the query is always in "string" form (fired by postman), so there is always no match with the select component's numeric submission data.

Detail please see below, any hint/insight will always be appreciated! 

Best, 
Tommy 

## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [x] Local deployment
    - Version: v2.0.0-beta.5
- Formio.js version: 4.9.23
- Frontend framework: none, just using postman to test query
- Browser: N/A
- Browser version: N/A

## Steps to Reproduce
1. use select component, refer to a resource X, with a field type "number".
![image](https://user-images.githubusercontent.com/30006459/80339740-987fbb80-885f-11ea-85b7-bd1dca48487e.png)
2. then "enter data" in that select component. 
![image](https://user-images.githubusercontent.com/30006459/80339936-f90ef880-885f-11ea-8767-ae5272946e32.png)
3. then you can observe in the "view data" that submission has been saved
![image](https://user-images.githubusercontent.com/30006459/80340029-252a7980-8860-11ea-89d5-d3135810929e.png)
4. then use postman to query the data - very strangely, the return is always empty...
![image](https://user-images.githubusercontent.com/30006459/80340067-3d9a9400-8860-11ea-92b1-5562ec450712.png)

## Expected behavior
at step4, the return data should return the submission with data.select = 2
## Observed behavior
very strangely, the return is always empty...

## Example
screenshot pls see above

**Comment by wag110894** [comment] 2020-04-27 14:00
@tmy2017 Can you provide a JSFiddle so that we can reproduce on our side?

**Comment by tmy2017** [comment] 2020-04-27 14:49
hi @wag110894 thx for replying! no prob! here you go with my JsFiddle, but I'm not sure will this help you more.
* https://jsfiddle.net/1ksu689L/
* ![image](https://user-images.githubusercontent.com/30006459/80385285-2bdbdf80-88a6-11ea-99de-a47982764671.png)


my objective is simply to query submission data by GET request. I now also reproduce the same issue on the portal.form.io so that you can also test it yourself (instead of my local). You can see my form definition as below
* https://fqrwpyqpmobffkh.form.io/ucca

and this is the data I have in the resource "ucca"
* ![image](https://user-images.githubusercontent.com/30006459/80385650-9ee55600-88a6-11ea-8c65-59b4a7e33d37.png)

so as you can see there is clearly a submission "2" (in numeric format), and my GET query just can not find it, he always returns empty array to me...

**Comment by wag110894** [comment] 2020-04-27 20:55
Can you try adding the Storage Type is equal to String in the data settings?

**Comment by tmy2017** [comment] 2020-04-28 03:43
Yes! I have already tried that and the query can return correct result. That’s my current workaround already. 

A little follow up question - but isn’t this “storage type” only exist for next.form.io’s UI? If I’m in old portal.form.io OR in my local open sourced formio, how do I enable this storage type = string?

**Comment by randallknutson** [comment] 2020-04-28 14:55
next.form.io will soon be our production portal (once we finish the last few bugs which is getting close!). You can already upgrade this app's renderer by upgrading ng-formio to the latest 4.x version in the formio-app-formio repository. We'd like to upgrade it there as well but haven't had the time to do it yet.

As for the original issue, it is actually incredibly difficult to solve this problem since we currently don't know if "2" coming in should be cast to a number or a string in both the querystring and the database. We are working on some solutions but don't have the ready yet.

**Comment by tmy2017** [comment] 2020-04-28 20:57
hi @randallknutson!  Got it, then I will just use the workaround for now (by forcing storage type to be a string). Still many thanks for your attention in this issue.

I have still one little question here - I tried to upgrade ```ng-formio``` in `bower.json` to 4.x version. But after I did `gulp serve`, I keep getting errors in my console as below pics. 

Could you share some tips on how can I upgrade to 4.x version for this ```formio-app-formio```? Any hints would be appreciated! 

-  ![image](https://user-images.githubusercontent.com/30006459/80536364-8d817400-89a2-11ea-86a9-880c55ec2166.png)
- ![image](https://user-images.githubusercontent.com/30006459/80536580-dfc29500-89a2-11ea-89c4-7323a0c87343.png)

**Comment by randallknutson** [comment] 2020-04-29 14:56
That error occurs when something goes wrong in defining the modules. I haven't done this in a while but if I remember correctly, you should remove ng-formio-builder as it was merged into ng-formio. Other than that you need to track down what is throwing the error that causes formio to not initialize correctly.

**Comment by tmy2017** [comment] 2020-05-01 04:16
hi @randallknutson, it's clear, many thanks for your help! 

(should I close this issue since I already have workaround and you are ware of the situation?)

**Comment by ddurham2** [comment] 2021-06-19 03:57
The workaround doesn't appear to be possible with a dropdown where the values are numeric.  There's no storage type option.

**Comment by daneformio** [comment] 2024-01-31 14:10
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!

**Closed by daneformio** 2024-01-31 14:10 UTC
Labels: bug
