### ISSUE TITLE
Node version check failed

### ISSUE THREAD

**Issue by AochiToxx** [formio/formio#634] opened 2018-08-17 17:50 UTC
I'm not sure if this is affecting anyone else. But following the readme.md just after the instruction to run `npm install`, it instructs to run `npm start` which runs `"start": "npm run version && node main.js",` from package.json. This should check if the currently installed node is beyond version 6 (i'm running version 8.2.1) if I'm understanding correctly but for me it fails, so I took out the `npm run version &&` leaving 
me with `"start": "node main.js",` and it seems to work fine. 

From what I see this shouldn't be failing so this is really just a note for someone that might be having a similar issue.

**Comment by travist** [comment] 2018-08-19 04:02
This will be fixed with next release. I am just going to remove this check. Should have the release out tonight.

Thanks.

**Comment by Sidiro23** [comment] 2024-01-31 14:34
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.

**Closed by Sidiro23** 2024-01-31 14:34 UTC
