### ISSUE TITLE
Google Drive - File storage connection

### ISSUE THREAD

**Issue by joe-jia** [formio/formio#1713] opened 2024-03-05 05:07 UTC
FormIO enterprise versionv8.3.2 formiojs version 4.17.2

Issue: Unauthorised error from on-prem formIO platform.
![image](https://github.com/formio/formio/assets/22853550/e561b773-db79-4e39-865d-4c33cc584d04)

Configuration: 
![image](https://github.com/formio/formio/assets/22853550/a69c2c71-5fad-4fd5-bef8-72e9851a4049)

![image](https://github.com/formio/formio/assets/22853550/b90ee8de-0cfd-4e54-bcce-9e57488d1e42)

Reference:
https://help.form.io/developers/integrations/file-storage#google-drive

Note: The authorisation is working on the postman when calling the Google Drive API e.g. https://www.googleapis.com/drive/v3/files/XYZ

Set up a google drive APIs web service

**Comment by daneformio** [comment] 2024-04-10 13:32
We have reproduced this issue and have created a ticket for internal tracking: FIO-8200

**Comment by daneformio** [comment] 2024-04-12 17:55
I am closing this ticket from open source, as this bug pertains to a packaged application in the enterprise platform. Please email support@form.io with inquiries about this ticket.

**Closed by daneformio** 2024-04-12 17:55 UTC

**Comment by daneformio** [comment] 2024-05-01 21:42
@joe-jia We were able to work around this by changing access permissions for the form to allow Anonymous and Authenticated submissions. You may also need to review the setup for Google Drive integration, which has changed since our documentation was created.
