### ISSUE TITLE
while using encapsulation: ViewEncapsulation.ShadowDom property, form-builder drag and drop is not working

### ISSUE THREAD

**Issue by pooja-waikar** [formio/formio#988] opened 2020-05-07 05:56 UTC
I trying to use **encapsulation: ViewEncapsulation.ShadowDom** property for my component to access only component css files, But when I use ShadowDom, form-builder drag and drop is not working.
I am not able to drag and drop components.

**Comment by randallknutson** [comment] 2020-05-07 14:33
You may be posting this in the wrong repo. This is the server repository and doesn't include any angular code. I'll reassign to the angular-formio repo which may be where your problem is.

**Comment by Sidiro23** [comment] 2024-01-31 14:39
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.

**Closed by Sidiro23** 2024-01-31 14:39 UTC
