### ISSUE TITLE
Unique and Required field for user and admin ressources

### ISSUE THREAD

**Issue by gismomtl** [formio/formio#720] opened 2019-01-07 17:39 UTC
Hi,
the default user and admin form/ressource does not required email field to be unique and required.
Is there any reason why?
if we change that to unique and required (and clean any potential faulty entries), is there any unknown issues we could face?
we cannot see any reason we could face... even if we implement additional role (besides admin/authenticated/anonymous)?

**Comment by randallknutson** [comment] 2019-01-08 15:54
This should be perfectly fine. Keep in mind though that if the email field is unique on both user and admin they are unique per resource. For example, the same email could exist in user and in admin but there couldn't be duplicates in user or admin.

**Comment by gismomtl** [comment] 2019-06-05 01:20
with latest version, when we set the ROOT_EMAIL  & ROOT_PASSWORD, installation is duplicating admin account.. even if the account already exists in the database and we set admin ressource with unique email...
so it's not working so far

**Comment by randallknutson** [comment] 2019-06-05 15:29
The process that installs the root user is very low level so it may be bypassing the checks. However, it is supposed to only run on empty databases. Is there a logic issue that is causing this to run when it shouldn't be?

Here is where the logic runs to determine if it should install or not. 
https://github.com/formio/formio/blob/86d7221b2970b5e59b6a27b49e1e6ec0cc68d008/server.js#L88-L115

In addition, you can set NO_INSTALL=true in an environment variable to stop it from doing the install.

**Comment by gismomtl** [comment] 2020-04-04 21:22
I tried to patch the formio installation (in the template folder)+ manually changed user/admin to have unique and required email.. however after a new install, user/admin email is back to default (not unique or required).
Having same admin email with multiple id is for my point of view an issue.. due to that, admin (idem for user) will not be able to see its previous submission.. as there are linked to the previous user/admin id.

Is it possible to have it changed or at least have an option in deployment parameter to make sure it  remains active after a new install??

**Comment by travist** [comment] 2020-04-06 14:54
@gismomtl I agree with your proposal. If you would like to make that change, then go ahead and make the modifications and submit a pull request. We will gladly accept it if it looks good to us.

**Comment by gismomtl** [comment] 2020-04-21 02:51
Hi, 
I tried to apply the changes but it doesnt seem to work.. so did I miss something???
Formio is deployed in a docker
- before upgrade with patch, user & admin email is set manually to required&unique
- version is patch in src/templates/default.json, email component is modified with:
              "unique": true,
              "required": true, // added
- redeploy the new formio version

but later we see the change is not there anymore..so far I'm not able to see why...

**Comment by travist** [comment] 2020-04-21 13:53
If you are using Open source server, then this is not deployed in a docker container. There are some builds out there that offer formio/formio in a container, and those will not be modifiable but you should be able to modify the code before you run it with "node main".

**Comment by gismomtl** [comment] 2020-04-21 14:21
My docker image is containing the master formio content, which I patched. So the src/templates/default.json is manually modified before executing the installation.
The only live content is the formio.js client which is downloaded.
So I don't understand so far which my patch is not working.. but if a PR is possible, fine.. I just need to find how to do so, so the patch will be permanent.

**Comment by gismomtl** [comment] 2020-06-26 15:18
can you confirm the PR is working on your side? on mine, with the PR or even before, even if the template file is modified to have user & admin email required and unique, the change in the UI is not visible.
I've to manually change that.. and in case of a docker redeployment, change has to be redone again and again.
There is something which doesnt apply/retain the change correctly...

**Comment by wag110894** [comment] 2020-06-26 15:40
@gismomtl 

We will ensure to add this to our next build and let you know if it is working on our side. Thank you again for your contribution to the Form.io Platform.

**Comment by gismomtl** [comment] 2020-07-09 11:54
Hi, have you been able to have the fix working?

**Comment by travist** [comment] 2020-07-09 21:10
Are you having problems with this with our Enterprise product or Open Source? We committed your PR into open source so it should be good to go there. If you are having issues with Enterprise, then it may be possible that we need to migrate this template over there.

**Comment by gismomtl** [comment] 2020-07-10 17:29
the issue is with the Open Source. We are deploying Formio in docker env.

**Comment by travist** [comment] 2020-07-13 14:54
We did pull in that pull request into the Open Source repository so maybe it is incomplete?... That was your fix so it may require a second look.

**Comment by ZenMasterJacob20011** [comment] 2024-01-24 14:31
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.

**Closed by ZenMasterJacob20011** 2024-01-24 14:31 UTC
