### ISSUE TITLE
have Dryrun = 1 query parm still return data object

### ISSUE THREAD

**Issue by StephenOTT** [formio/formio#454] opened 2017-11-17 17:40 UTC
Currently when you use `dryrun=1` for a valid submission you get a `true` and status code 200.

But there are scenarios where you want to see the data that was returned.  Example with persistent config of a field.  

![persistent](https://user-images.githubusercontent.com/1994838/32960794-3f48822a-cb94-11e7-93c8-5013193d1b11.png)

You want to see the data object returned because there is fields that you want to know what was persisted and not:

```
{
    "modified": "2017-11-17T17:38:24.819Z",
    "data": {
        "sendTextMsg": "yes",
        "lastName": "Dirt"
    },
    "form": "59c2e5d197756f00067a5b49",
    "created": "2017-11-17T17:38:24.818Z",
    "_id": "5a0f1e9097756f00067a5b7e",
    "externalIds": [],
    "access": [],
    "roles": [],
    "owner": null
}
```

We would want to see at least the dat a field returned.

But would be nice if the `dryrun` could have additional option to have the data returned?  like a `withDataReturned = 1`

**Comment by StephenOTT** [comment] 2017-11-17 17:40
@travist

**Comment by travist** [comment] 2017-11-28 16:10
I believe this should be resolved with the latest version. @randallknutson made a change that returns the JSON of the submission that "would" be saved using dryrun, I believe. @randallknutson maybe you can chime in here?

**Comment by StephenOTT** [comment] 2017-11-30 19:18
So it seems this is partially implemented in lastest master as of today (Nov 30).

Given the following scenario:

![screen shot 2017-11-30 at 2 12 39 pm](https://user-images.githubusercontent.com/1994838/33450055-a01af206-d5d8-11e7-9696-7f29c7e6c8b6.png)
![screen shot 2017-11-30 at 2 12 37 pm](https://user-images.githubusercontent.com/1994838/33450057-a29b6f10-d5d8-11e7-9a9d-826357986a14.png)


Where there is a First Name and a Last Name text field.  The First Name is required, and the Last Name is Not persisted as per the image.

If you do a dry run you get the following:

![screen shot 2017-11-30 at 2 14 16 pm](https://user-images.githubusercontent.com/1994838/33450127-d131f7fe-d5d8-11e7-91d2-4e43fbe59ea2.png)

Extra fields are not returned, But the Last Name is returned with the submitted value.

BUT if you delete the Form Action of making a submission and run the form without the dry run:

![screen shot 2017-11-30 at 2 16 26 pm](https://user-images.githubusercontent.com/1994838/33450251-252d6a0a-d5d9-11e7-8177-e778049af239.png)

you do get the expected fields returned in the body response

**Comment by StephenOTT** [comment] 2017-11-30 19:25
@travist is this what you were expecting?  It looks like `dryrun` does not go through the full cycle of validations/data checks

**Comment by travist** [comment] 2017-12-01 00:20
That is bizarre and not expected behavior. Dry run should change based on actions. Looks like a bug. @randallknutson was the last to change this. Maybe he has an idea...

**Comment by travist** [comment] 2017-12-01 00:21
I mean "not change"...

**Comment by StephenOTT** [comment] 2018-03-08 19:48
@randallknutson @travist any movement on this?

**Comment by Sidiro23** [comment] 2024-01-31 14:19
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!

**Closed by Sidiro23** 2024-01-31 14:19 UTC
