### ISSUE TITLE
docker version not working MODULE_NOT_FOUND

### ISSUE THREAD

**Issue by changchichung** [formio/formio#1696] opened 2024-02-05 06:38 UTC
docker logs
```
2024-02-05 14:35:46 [administrator@ubuntu-jammy-server formio  master ]$ docker logs -f formio-formio-1
node:internal/modules/cjs/loader:1147
  throw err;
  ^

Error: Cannot find module 'mongoose'
Require stack:
- /app/src/util/util.js
- /app/main.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/app/src/util/util.js:3:18)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/app/src/util/util.js', '/app/main.js' ]
}

```

any suggestions ?

**Comment by brendanbond** [comment] 2024-02-05 15:15
Steps to reproduce? Are you modifying the Dockerfile at all? The dependencies should be installed on the image.

**Comment by ubed-ali** [comment] 2024-02-13 15:02
I simply cloned the repo and ran the command `npm install && docker-compose up`. Unfortunately, I'm still encountering the same error. Are there any workarounds, or would using specific versions of npm and node be helpful?

**Comment by brendanbond** [comment] 2024-02-13 15:54
I will look into this, that's pretty strange

**Comment by ubed-ali** [comment] 2024-02-14 04:58
Node: V9.8.0
npm: 5.6.0

**Comment by brendanbond** [comment] 2024-02-14 16:24
I still can't reproduce this, any other information you can provide? OS, etc.?

**Comment by erikpb** [comment] 2024-02-14 18:49
Had the same issue, adding python3 to the Dockerfile solved it:

```
RUN apk update && \
    apk upgrade && \
    apk add make && \
    apk add python3 && \
    apk add g++
```

**Comment by ubed-ali** [comment] 2024-02-19 09:25
@erikpb i tried by adding python3 but still facing same error:

> formio_1  | node:internal/modules/cjs/loader:1147
> formio_1  |   throw err;
> formio_1  |   ^
> formio_1  | 
> formio_1  | Error: Cannot find module 'formio-workers/workers/util'
> formio_1  | Require stack:
> formio_1  | - /app/src/util/util.js
> formio_1  | - /app/main.js
> formio_1  |     at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
> formio_1  |     at Module._load (node:internal/modules/cjs/loader:985:27)
> formio_1  |     at Module.require (node:internal/modules/cjs/loader:1235:19)
> formio_1  |     at require (node:internal/modules/helpers:176:18)
> formio_1  |     at Object.<anonymous> (/app/src/util/util.js:8:21)
> formio_1  |     at Module._compile (node:internal/modules/cjs/loader:1376:14)
> formio_1  |     at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
> formio_1  |     at Module.load (node:internal/modules/cjs/loader:1207:32)
> formio_1  |     at Module._load (node:internal/modules/cjs/loader:1023:12)
> formio_1  |     at Module.require (node:internal/modules/cjs/loader:1235:19) {
> formio_1  |   code: 'MODULE_NOT_FOUND',
> formio_1  |   requireStack: [ '/app/src/util/util.js', '/app/main.js' ]
> formio_1  | }
> formio_1  | 
> formio_1  | Node.js v20.11.0
> formio_formio_1 exited with code 1

**Comment by brendanbond** [comment] 2024-02-19 16:26
Hi @erikpb @changchichung @ubed-ali I've opened a pull request #1703 that should address these issues. If you get a chance, pull down that branch and see if it fixes your issues. It's a US holiday today, but I'll try to get it reviewed and merged this week.

**Comment by erikpb** [comment] 2024-02-20 08:38
That PR fixes the issue @brendanbond, thank you very much.

**Closed** 2024-02-21 14:21 UTC
