### ISSUE TITLE
Missing node-paginate-anything when running "npm start"

### ISSUE THREAD

**Issue by max-allan-surevine** [formio/formio#615] opened 2018-07-05 15:24 UTC
[ec2-user@ip-10-0-20-160 data]$ git clone https://github.com/formio/formio.git
    Cloning into 'formio'...
    remote: Counting objects: 9593, done.
    remote: Compressing objects: 100% (58/58), done.
    remote: Total 9593 (delta 38), reused 51 (delta 29), pack-reused 9506
    Receiving objects: 100% (9593/9593), 2.55 MiB | 5.91 MiB/s, done.
    Resolving deltas: 100% (6749/6749), done.
    [ec2-user@ip-10-0-20-160 data]$ cd formio/
    [ec2-user@ip-10-0-20-160 formio]$ npm install

    > bcrypt@2.0.1 install /data/formio/node_modules/bcrypt
    > node-pre-gyp install --fallback-to-build

    [bcrypt] Success: "/data/formio/node_modules/bcrypt/lib/binding/bcrypt_lib.node" is installed via remote

    > pre-commit@1.2.2 install /data/formio/node_modules/pre-commit
    > node install.js

    > spawn-sync@1.0.15 postinstall /data/formio/node_modules/spawn-sync
    > node postinstall

    > nunjucks@3.1.3 postinstall /data/formio/node_modules/nunjucks
    > node postinstall-build.js src

    > nodemon@1.17.5 postinstall /data/formio/node_modules/nodemon
    > node bin/postinstall || exit 0

    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
    npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

    added 777 packages in 15.313s
    [ec2-user@ip-10-0-20-160 formio]$ 
    [ec2-user@ip-10-0-20-160 formio]$ npm start

    > formio@1.31.1 start /data/formio
    > npm run version && node main.js

    > formio@1.31.1 version /data/formio
    > check-node-version --node '>=6.0.0'

      __  __                          _       __
     / / / _| ___  _ __ _ __ ___     (_) ___  \ \
    / / | |_ / _ \| '__| '_ ` _ \    | |/ _ \  \ \
    \ \ |  _| (_) | |  | | | | | | _ | | (_) | / /
     \_\|_|  \___/|_|  |_| |_| |_|(_)|_|\___/ /_/

    Welcome to the Form.io application server!

      - Help: https://help.form.io
      - Code: https://github.com/formio
      - Love: https://form.io

    Checking for db install.
     > Install found. No install necessary.

    Checking for db schema updates.
     > No updates found.

    Initializing API Server.
     > Mongo connection established.
    /data/formio/node_modules/mongodb/lib/mongo_client.js:806
              throw err;
              ^

    Error: Cannot find module 'node-paginate-anything'
        at Function.Module._resolveFilename (module.js:547:15)
        at Function.Module._load (module.js:474:25)
        at Module.require (module.js:596:17)
        at require (internal/module.js:11:18)
        at Object.<anonymous> (/data/formio/node_modules/resourcejs/Resource.js:4:18)
        at Module._compile (module.js:652:30)
        at Object.Module._extensions..js (module.js:663:10)
        at Module.load (module.js:565:32)
        at tryModuleLoad (module.js:505:12)
        at Function.Module._load (module.js:497:3)
        at Module.require (module.js:596:17)
        at require (internal/module.js:11:18)
        at Object.<anonymous> (/data/formio/src/resources/FormResource.js:3:18)
        at Module._compile (module.js:652:30)
        at Object.Module._extensions..js (module.js:663:10)
        at Module.load (module.js:565:32)
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! formio@1.31.1 start: `npm run version && node main.js`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the formio@1.31.1 start script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

    npm ERR! A complete log of this run can be found in:
    npm ERR!     /home/ec2-user/.npm/_logs/2018-07-05T15_20_42_270Z-debug.log
    [ec2-user@ip-10-0-20-160 formio]$ git describe
    v1.29.2-34-g33402ca

**Comment by max-allan-surevine** [comment] 2018-07-05 15:25
[ec2-user@ip-10-0-20-160 formio]$ npm install node-paginate-anything
Seems to fix it, but isn't that what `npm install` is supposed to do for me: find&install all dependencies?

**Comment by rmckeel** [comment] 2018-12-21 18:56
For what it's worth @max-allan-surevine, I had the same issue on a Heroku build.  Very aggravating that `npm install` did not properly install node-paginate-anything.  Rather, I found that sometimes it would install `node-paginate-anything`, sometimes it would not, even in the presence of a package-lock.json file that did not change.  Not sure why the variance from one week to the next, but it is unsettling.  Note this was on an old version of Formio service where we had a custom package-lock.json (before one was checked in on this repo).

To resolve, I decided to migrate the package-lock.json to yarn.lock and use the Yarn package management system, which resolved.  Fortunately, `yarn import` parses and in my case acceptably migrated the NPM lock to a new Yarn lock.

Hope that helps.  Our plan is to do a `yarn import` for any future Formio updates, because NPM has been found unreliable and inconsistent even with a package lock for our use of it.

**Comment by randallknutson** [comment] 2018-12-21 21:32
I don't think we've seen this issue before. Do you think it is an issue with node-paginate-anything or our package-lock.json?

**Comment by rmckeel** [comment] 2018-12-21 22:03
@randallknutson Good question.  This project is on an older version of Formio service that is before you had package-lock.json checked in, so we locked resourcejs to version 1.11.0.  The issue was npm built it one way one time, and didn't include the sub-dependency of resource.js the second time, even though it was clearly listed in package-lock.json.

Honestly, this seems like a bug with npm.  Per @max-allan-surevine, npm should resolve sub-dependencies, and in this case (on a Heroku machine with package.json and package-lock.json), it would build unpredictably.  Switching to yarn solved it in our case, though I realize that may not be feasible for the library to switch to Yarn.

**Comment by Sidiro23** [comment] 2024-01-31 14:34
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.

**Closed by Sidiro23** 2024-01-31 14:34 UTC
